# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-24 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premios_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_pic',
            field=models.ImageField(upload_to='project_pics/'),
        ),
    ]
