# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-25 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premios_app', '0003_auto_20191124_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_site',
            field=models.CharField(default='www.google.com', max_length=256),
            preserve_default=False,
        ),
    ]
