# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-27 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('premios_app', '0004_project_live_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_site',
            field=models.URLField(max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_pic',
            field=pyuploadcare.dj.models.ImageField(),
        ),
    ]
